# Generated by Django 5.2.6 on 2025-09-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('cnpj', models.CharField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
