# Generated by Django 5.2.6 on 2025-09-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gempresas', '0002_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('email', models.CharField()),
                ('senha', models.CharField()),
            ],
        ),
    ]
