# Generated by Django 5.2.6 on 2025-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gempresas', '0003_user_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='grupo',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regime_federal',
            field=models.CharField(default='simples'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(),
        ),
    ]
