# Generated by Django 5.2.6 on 2025-09-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gempresas', '0004_empresa_grupo_empresa_regime_federal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='regime_federal',
            field=models.CharField(),
        ),
    ]
