# Generated by Django 5.2.6 on 2025-09-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gempresas', '0005_alter_empresa_regime_federal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa'), ('S', 'Suspensa')], default='A', max_length=1),
        ),
    ]
